name: CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build

    - name: Benchmark
      run: dotnet run -c Release --project AsyncEnumerableSource.Benchmarks --no-build

    - name: Publish Benchmarks
      uses: actions/upload-artifact@v4
      with:
        name: benchmarks.md
        path: AsyncEnumerableSource.Benchmarks/BenchmarkDotNet.Artifacts/results/AsyncEnumerableSource.Benchmarks.AsyncEnumerableSourceBenchmarks-report-github.md
